<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="109" started-at="2016-01-11T16:25:12Z" finished-at="2016-01-11T16:25:12Z">
    <groups>
      <group name="unit">
        <method signature="BaseProviderMetadataTest.testAllContains()[pri:0, instance:org.jclouds.aws.ec2.AWSEC2ProviderTest@f2818d]" name="testAllContains" class="org.jclouds.providers.internal.BaseProviderMetadataTest"/>
        <method signature="BaseProviderMetadataTest.testOfApiContains()[pri:0, instance:org.jclouds.aws.ec2.AWSEC2ProviderTest@f2818d]" name="testOfApiContains" class="org.jclouds.providers.internal.BaseProviderMetadataTest"/>
        <method signature="BaseProviderMetadataTest.testTransformableToContains()[pri:0, instance:org.jclouds.aws.ec2.AWSEC2ProviderTest@f2818d]" name="testTransformableToContains" class="org.jclouds.providers.internal.BaseProviderMetadataTest"/>
        <method signature="BaseProviderMetadataTest.testWithId()[pri:0, instance:org.jclouds.aws.ec2.AWSEC2ProviderTest@f2818d]" name="testWithId" class="org.jclouds.providers.internal.BaseProviderMetadataTest"/>
      </group> <!-- unit -->
    </groups>
    <test name="Default test" duration-ms="109" started-at="2016-01-11T16:25:12Z" finished-at="2016-01-11T16:25:12Z">
      <class name="org.jclouds.aws.ec2.AWSEC2ProviderTest">
        <test-method status="FAIL" signature="testAllContains()[pri:0, instance:org.jclouds.aws.ec2.AWSEC2ProviderTest@f2818d]" name="testAllContains" duration-ms="47" started-at="2016-01-12T00:25:12Z" finished-at="2016-01-12T00:25:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[{id=aws-ec2, name=Amazon Elastic Compute Cloud (EC2), api={id=aws-ec2, name=Amazon-specific EC2 API, views=[org.jclouds.aws.ec2.compute.AWSEC2ComputeServiceContext], endpointName=https endpoint, identityName=Access Key ID, credentialName=Optional.of(Secret Access Key), documentation=http://docs.amazonwebservices.com/AWSEC2/latest/APIReference, api=interface org.jclouds.aws.ec2.AWSEC2Api}, endpoint=https://ec2.us-east-1.amazonaws.com, console=Optional.of(https://console.aws.amazon.com/ec2/home), homepage=Optional.of(http://aws.amazon.com/ec2), linkedServices=[aws-ec2, aws-elb, aws-cloudwatch, aws-s3, aws-simpledb], iso3166Codes=[US-VA, US-CA, US-OR, BR-SP, IE, DE-HE, SG, AU-NSW, JP-13]} not found in []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: {id=aws-ec2, name=Amazon Elastic Compute Cloud (EC2), api={id=aws-ec2, name=Amazon-specific EC2 API, views=[org.jclouds.aws.ec2.compute.AWSEC2ComputeServiceContext], endpointName=https endpoint, identityName=Access Key ID, credentialName=Optional.of(Secret Access Key), documentation=http://docs.amazonwebservices.com/AWSEC2/latest/APIReference, api=interface org.jclouds.aws.ec2.AWSEC2Api}, endpoint=https://ec2.us-east-1.amazonaws.com, console=Optional.of(https://console.aws.amazon.com/ec2/home), homepage=Optional.of(http://aws.amazon.com/ec2), linkedServices=[aws-ec2, aws-elb, aws-cloudwatch, aws-s3, aws-simpledb], iso3166Codes=[US-VA, US-CA, US-OR, BR-SP, IE, DE-HE, SG, AU-NSW, JP-13]} not found in []
	at org.jclouds.providers.internal.BaseProviderMetadataTest.testAllContains(BaseProviderMetadataTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAllContains -->
        <test-method status="FAIL" signature="testOfApiContains()[pri:0, instance:org.jclouds.aws.ec2.AWSEC2ProviderTest@f2818d]" name="testOfApiContains" duration-ms="0" started-at="2016-01-12T00:25:12Z" finished-at="2016-01-12T00:25:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[{id=aws-ec2, name=Amazon Elastic Compute Cloud (EC2), api={id=aws-ec2, name=Amazon-specific EC2 API, views=[org.jclouds.aws.ec2.compute.AWSEC2ComputeServiceContext], endpointName=https endpoint, identityName=Access Key ID, credentialName=Optional.of(Secret Access Key), documentation=http://docs.amazonwebservices.com/AWSEC2/latest/APIReference, api=interface org.jclouds.aws.ec2.AWSEC2Api}, endpoint=https://ec2.us-east-1.amazonaws.com, console=Optional.of(https://console.aws.amazon.com/ec2/home), homepage=Optional.of(http://aws.amazon.com/ec2), linkedServices=[aws-ec2, aws-elb, aws-cloudwatch, aws-s3, aws-simpledb], iso3166Codes=[US-VA, US-CA, US-OR, BR-SP, IE, DE-HE, SG, AU-NSW, JP-13]} not found in []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: {id=aws-ec2, name=Amazon Elastic Compute Cloud (EC2), api={id=aws-ec2, name=Amazon-specific EC2 API, views=[org.jclouds.aws.ec2.compute.AWSEC2ComputeServiceContext], endpointName=https endpoint, identityName=Access Key ID, credentialName=Optional.of(Secret Access Key), documentation=http://docs.amazonwebservices.com/AWSEC2/latest/APIReference, api=interface org.jclouds.aws.ec2.AWSEC2Api}, endpoint=https://ec2.us-east-1.amazonaws.com, console=Optional.of(https://console.aws.amazon.com/ec2/home), homepage=Optional.of(http://aws.amazon.com/ec2), linkedServices=[aws-ec2, aws-elb, aws-cloudwatch, aws-s3, aws-simpledb], iso3166Codes=[US-VA, US-CA, US-OR, BR-SP, IE, DE-HE, SG, AU-NSW, JP-13]} not found in []
	at org.jclouds.providers.internal.BaseProviderMetadataTest.testOfApiContains(BaseProviderMetadataTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOfApiContains -->
        <test-method status="FAIL" signature="testTransformableToContains()[pri:0, instance:org.jclouds.aws.ec2.AWSEC2ProviderTest@f2818d]" name="testTransformableToContains" duration-ms="0" started-at="2016-01-12T00:25:12Z" finished-at="2016-01-12T00:25:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[{id=aws-ec2, name=Amazon Elastic Compute Cloud (EC2), api={id=aws-ec2, name=Amazon-specific EC2 API, views=[org.jclouds.aws.ec2.compute.AWSEC2ComputeServiceContext], endpointName=https endpoint, identityName=Access Key ID, credentialName=Optional.of(Secret Access Key), documentation=http://docs.amazonwebservices.com/AWSEC2/latest/APIReference, api=interface org.jclouds.aws.ec2.AWSEC2Api}, endpoint=https://ec2.us-east-1.amazonaws.com, console=Optional.of(https://console.aws.amazon.com/ec2/home), homepage=Optional.of(http://aws.amazon.com/ec2), linkedServices=[aws-ec2, aws-elb, aws-cloudwatch, aws-s3, aws-simpledb], iso3166Codes=[US-VA, US-CA, US-OR, BR-SP, IE, DE-HE, SG, AU-NSW, JP-13]} not found in [] for org.jclouds.aws.ec2.compute.AWSEC2ComputeServiceContext]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: {id=aws-ec2, name=Amazon Elastic Compute Cloud (EC2), api={id=aws-ec2, name=Amazon-specific EC2 API, views=[org.jclouds.aws.ec2.compute.AWSEC2ComputeServiceContext], endpointName=https endpoint, identityName=Access Key ID, credentialName=Optional.of(Secret Access Key), documentation=http://docs.amazonwebservices.com/AWSEC2/latest/APIReference, api=interface org.jclouds.aws.ec2.AWSEC2Api}, endpoint=https://ec2.us-east-1.amazonaws.com, console=Optional.of(https://console.aws.amazon.com/ec2/home), homepage=Optional.of(http://aws.amazon.com/ec2), linkedServices=[aws-ec2, aws-elb, aws-cloudwatch, aws-s3, aws-simpledb], iso3166Codes=[US-VA, US-CA, US-OR, BR-SP, IE, DE-HE, SG, AU-NSW, JP-13]} not found in [] for org.jclouds.aws.ec2.compute.AWSEC2ComputeServiceContext
	at org.jclouds.providers.internal.BaseProviderMetadataTest.testTransformableToContains(BaseProviderMetadataTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransformableToContains -->
        <test-method status="FAIL" signature="testWithId()[pri:0, instance:org.jclouds.aws.ec2.AWSEC2ProviderTest@f2818d]" name="testWithId" duration-ms="15" started-at="2016-01-12T00:25:12Z" finished-at="2016-01-12T00:25:12Z">
          <exception class="java.util.NoSuchElementException">
            <full-stacktrace>
              <![CDATA[java.util.NoSuchElementException
	at com.google.common.collect.AbstractIterator.next(AbstractIterator.java:154)
	at com.google.common.collect.Iterators.find(Iterators.java:712)
	at com.google.common.collect.Iterables.find(Iterables.java:642)
	at org.jclouds.providers.Providers.withId(Providers.java:99)
	at org.jclouds.providers.internal.BaseProviderMetadataTest.testWithId(BaseProviderMetadataTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.util.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWithId -->
      </class> <!-- org.jclouds.aws.ec2.AWSEC2ProviderTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
