<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="fdp" name="org.jclouds.ecs.filters.QuerySignerTest" tests="4" failures="0" timestamp="10 Jan 2016 05:16:49 GMT" time="0.216" errors="4">
  <testcase name="testCreateStringToSign" time="0.031" classname="org.jclouds.ecs.filters.QuerySignerTest">
    <error type="java.lang.AssertionError" message="expected [apikey=apikey&amp;Action=DescribeInstances] but found [accesskeyid=bnf9nnddfctwm5mf&amp;action=describeinstances&amp;signaturemethod=hmac-sha1&amp;signaturenonce=427422296&amp;signatureversion=1.0]">
      <![CDATA[java.lang.AssertionError: expected [apikey=apikey&Action=DescribeInstances] but found [accesskeyid=bnf9nnddfctwm5mf&action=describeinstances&signaturemethod=hmac-sha1&signaturenonce=427422296&signatureversion=1.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at org.jclouds.ecs.filters.QuerySignerTest.testCreateStringToSign(QuerySignerTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testCreateStringToSign -->
  <testcase name="testFilterTwice" time="0.000" classname="org.jclouds.ecs.filters.QuerySignerTest">
    <error type="java.lang.AssertionError" message="expected [GET https://ecs.aliyuncs.com/?command=listZones&amp;apiKey=apiKey&amp;signature=2UG8AcnMaozL3BINdjgkJ%2BRzjEY%3D HTTP/1.1] but found [GET https://ecs.aliyuncs.com/?command=listZones&amp;AccessKeyId=bnF9nNdDFCTwM5mF&amp;SignatureMethod=HMAC-SHA1&amp;SignatureVersion=1.0&amp;SignatureNonce=797192145&amp;Signature=RRRlK3EVH5wek%2BKlG0hKuSHuA1I%3D HTTP/1.1]">
      <![CDATA[java.lang.AssertionError: expected [GET https://ecs.aliyuncs.com/?command=listZones&apiKey=apiKey&signature=2UG8AcnMaozL3BINdjgkJ%2BRzjEY%3D HTTP/1.1] but found [GET https://ecs.aliyuncs.com/?command=listZones&AccessKeyId=bnF9nNdDFCTwM5mF&SignatureMethod=HMAC-SHA1&SignatureVersion=1.0&SignatureNonce=797192145&Signature=RRRlK3EVH5wek%2BKlG0hKuSHuA1I%3D HTTP/1.1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at org.jclouds.ecs.filters.QuerySignerTest.testFilterTwice(QuerySignerTest.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testFilterTwice -->
  <testcase name="testFilter" time="0.185" classname="org.jclouds.ecs.filters.QuerySignerTest">
    <error type="java.lang.AssertionError" message="expected [GET https://ecs.aliyuncs.com/?command=listZones&amp;apiKey=apiKey&amp;signature=2UG8AcnMaozL3BINdjgkJ%2BRzjEY%3D HTTP/1.1] but found [GET https://ecs.aliyuncs.com/?command=listZones&amp;AccessKeyId=bnF9nNdDFCTwM5mF&amp;SignatureMethod=HMAC-SHA1&amp;SignatureVersion=1.0&amp;SignatureNonce=1264703181&amp;Signature=7v%2BbPR7E/1xD0y8u/pJVFBQGTw0%3D HTTP/1.1]">
      <![CDATA[java.lang.AssertionError: expected [GET https://ecs.aliyuncs.com/?command=listZones&apiKey=apiKey&signature=2UG8AcnMaozL3BINdjgkJ%2BRzjEY%3D HTTP/1.1] but found [GET https://ecs.aliyuncs.com/?command=listZones&AccessKeyId=bnF9nNdDFCTwM5mF&SignatureMethod=HMAC-SHA1&SignatureVersion=1.0&SignatureNonce=1264703181&Signature=7v%2BbPR7E/1xD0y8u/pJVFBQGTw0%3D HTTP/1.1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at org.jclouds.ecs.filters.QuerySignerTest.testFilter(QuerySignerTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testFilter -->
  <testcase name="testCreateStringToSignWithBrackets" time="0.000" classname="org.jclouds.ecs.filters.QuerySignerTest">
    <error type="java.lang.AssertionError" message="expected [apikey=apikey&amp;command=deployvirtualmachine&amp;iptonetworklist[0].ip=127.0.0.1&amp;iptonetworklist[0].networkid=1] but found [accesskeyid=bnf9nnddfctwm5mf&amp;signaturemethod=hmac-sha1&amp;signaturenonce=1506966095&amp;signatureversion=1.0&amp;command=deployvirtualmachine&amp;iptonetworklist[0].ip=127.0.0.1&amp;iptonetworklist[0].networkid=1]">
      <![CDATA[java.lang.AssertionError: expected [apikey=apikey&command=deployvirtualmachine&iptonetworklist[0].ip=127.0.0.1&iptonetworklist[0].networkid=1] but found [accesskeyid=bnf9nnddfctwm5mf&signaturemethod=hmac-sha1&signaturenonce=1506966095&signatureversion=1.0&command=deployvirtualmachine&iptonetworklist[0].ip=127.0.0.1&iptonetworklist[0].networkid=1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at org.jclouds.ecs.filters.QuerySignerTest.testCreateStringToSignWithBrackets(QuerySignerTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testCreateStringToSignWithBrackets -->
</testsuite> <!-- org.jclouds.ecs.filters.QuerySignerTest -->
